inherit_from: .rubocop_todo.yml

AllCops:
  # 除外するディレクトリを設定。例えばschemaやmigrationファイルなどは書き直すことが少ないため、検知対象外に
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'lib/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    # Rails向けのRails copsを実行。"rubocop -R"と同じ
  Rails:
    enabled: true

  # "Missing top-level class documentation comment."を無効
  Style/Documentation:
    Enabled: false
  
  # コメントにはアスキー記号のみを使用してください
  AsciiComments:
    Enabled: false

  # "Prefer single-quoted strings when you don't need string interpolation or special symbols."を無効
  Style/StringLiterals:
    Enabled: false

  # "Line is too long"を無効
  Metrics/LineLength:
    Enabled: false